### ISSUE TITLE
Wrapping text

### ISSUE THREAD

**Issue by chonigman** [ajimix/Input-Framer#13]
This is more of a question than an issue. Is it possible to get the text to wrap within the size of the input?

Pretty new to Framer and Cofeescript, but if not available, I may take a try at it. 

Thanks.

**Comment by ajimix** [comment]
Hey @KingWalrus an `input` is not designed for this purpose. If you want to have the text wrap on it, you should use a textarea (and this module currently doesn't support textarea).

But you can "hack" a little bit your input to wrap the text around it. As I said is not very good to do as the `input` was not created for that purpose, but if you like to hack it, here is the code :)

```coffeescript
{Input} = require "input"

someInput = new Input
	setup: true
	height: 300
someInput.style =
	"word-wrap": "break-word"
	"word-break": "break-word"
```

If you feel adventurous and you want to adapt the code of this module to allow textareas too, go ahead and make a pull request, I'll be happy to review it and merge it :)

**Comment by chonigman** [comment]
Awesome. Thanks for getting back to me. I actually found another module that does text area. I might propose a PR that makes it available as a type of input here. We'll see if I have enough time.
