### ISSUE TITLE
Select content with .setSelectionRange()

### ISSUE THREAD

**Issue by bildlich** [ajimix/Input-Framer#14]
I would like the value to be selected when tapping the field:

    myInput.onFocus ->
        this.setSelectionRange(0, this.value.length-1)

Unfortunately, this doesn't do anything.

How can I select the input's content when tapping it?

**Comment by ajimix** [comment]
Do you want to select the full text or only a part?

For the full input this should work:
```coffeescript
input.onFocus ->
  input.focus()
```

**Comment by ajimix** [comment]
This should work:

```coffeescript
myInput.onFocus ->
  @input.select() # For browsers
  @input.setSelectionRange 0, @input.value.length # For mobile safari
```

I haven't tested it, so please tell me if it doesn't work

**Comment by bildlich** [comment]
It doesn't. I added a bit more code for context:

	@valueLayer = new InputModule.Input
		parent: @textLayerGroup
		text: '110'
		setup: false
		virtualKeyboard: false
		padding: 0
		type: "number"
		fontSize: 26*2
		width: @textLayerGroup.width
		goButton: false
		x: Align.center()
		y: 72
	# Select number when tapping input field
	@valueLayer.onFocus ->
		@input.select() # For browsers
		@input.setSelectionRange 0, @input.value.length # For mobile safari

When tapping the field: "TypeError: undefined is not an object (evaluating this.object.select)."

**Comment by ajimix** [comment]
Ok sorry, now I made a test, this works:

```coffeescript
myInput.onFocus ->
	Utils.delay .1, =>
		@select() # For browsers
		@setSelectionRange 0, @value.length # For mobile safari
```

You need to add a small delay or it will be deselected after it's selected. Adding this 0.1 delay makes it work properly :)

**Comment by bildlich** [comment]
Thanks, this works!
