### ISSUE TITLE
Turn off the keyboard

### ISSUE THREAD

**Issue by daviddiamond1** [ajimix/Input-Framer#17]
Hey, great module it's been really useful! Is there a way to just disable the keyboard completely? I've tried `keyboard = false` but no luck.

Cheers.

**Comment by ajimix** [comment]
Hey @daviddiamond1 I'm curious, what is the use case of completely removing the keyboard? I mean, why do you want an input where you can't write?

**Comment by daviddiamond1** [comment]
@ajimix I want to be able to turn off the virtual keyboard, for web

**Comment by ajimix** [comment]
Oh ok, you should use the `virtualKeyboard` option. Like this:

```coffeescript
input = new InputModule.Input
  virtualKeyboard: false # Enable or disable virtual keyboard for when viewing on computer
```

I'm closing this issue. Please reopen it if you still have problems.

**Comment by daviddiamond1** [comment]
Ah, thanks Adria, might be worth adding to the list of options in the readme too 👍

**Comment by ajimix** [comment]
It was already there, it's the second option :)

**Comment by daviddiamond1** [comment]
🤦‍♂️
