### ISSUE TITLE
Input type not swapping

### ISSUE THREAD

**Issue by nathanbiehl** [ajimix/Input-Framer#20]
Noticing that the input "type" is only being set during creation. This is prevent us from swapping between "password" and "text" types with our login mock-up's "Show"/"Hide" password.

**Comment by ajimix** [comment]
Hey @nathanbiehl that's the nature of the input.

What I suggest you do is to create two inputs, one is the password hidden and the other visible.
- Make the password visible hidden so is not seen by default.
- On the input change event of the hidden, update the password visible value with the same text.
- Once you click on "show", make the one with the password visible, shown and the passwork masked hidden and the other way around.

I hope it helps :)

**Comment by nathanbiehl** [comment]
@ajimix I'll give that a go. Won't work with my current input validation, but I think I can find a work around. Thanks for the quick reply!
