### ISSUE TITLE
Multi-line

### ISSUE THREAD

**Issue by Ciars** [ajimix/Input-Framer#22]
Hey, big fan of your work.
This is not so much an issue as a suggestion. I was looking around for a way to create a multi-line input in Framer. The correct approach on the web is to use a html 'textarea' rather than an 'input', as your module uses.

Well I had peek inside your modules code, changed the following, and it just worked beautifully.

from: @input = document.createElement "input"
to: @input = document.createElement "textarea"

Could it perhaps be an option in your constructor?
Cheers

**Comment by ajimix** [comment]
Hey @Ciars thanks for your research. Someone in the past also requested this #13 
I'm not sure if only changing the constructor is enough, I would have to do some research on that. If you want to test if all the options of the module work with textarea, then I'll be happy to implement the change in the constructor as currently, I don't have enough time to test everything with a textarea.

Again, thanks for the time :)

**Comment by ajimix** [comment]
This is fixed on #30
