### ISSUE TITLE
Close keyboard

### ISSUE THREAD

**Issue by OskarMG** [ajimix/Input-Framer#24]
Hi. I'm trying to close the keyboard in the mobile version by doing tap on another different element from the "Done button". For example, when I finish typing the inputs I want to tap the "login" button and close the mobile keyboard ... Help

**Comment by ajimix** [comment]
Hello @OskarMG does that happen on Framer desktop or only on when you are trying your prototype on the mobile? Can you share a small prototype with an example?
Thanks

**Comment by OskarMG** [comment]
It only happens on the mobile.

[keyboard_Input_test.framer.zip](https://github.com/ajimix/Input-Framer/files/1353542/keyboard_Input_test.framer.zip)

**Comment by ajimix** [comment]
Ok I see, well the thing is that when you are tapping that layer, the focus is still at the input, you can easily solve that by using the blur on the inputs like the following code:
```coffeescript
btn_login.onTap ->
	if userInput.value == "" || passInput.value == ""
		return false
	else if userInput.value != "" || passInput.value != ""
		flow.showNext(onBoarding)
		userInput.input.blur()
		passInput.input.blur()
```

I'm closing the issue. Please reopen if you need more help on this.

**Comment by OskarMG** [comment]
Excellent! Thank you very much.

**Comment by OskarMG** [comment]
Hi bro. How can I set a maxLength inputs to the input field

**Comment by ajimix** [comment]
@OskarMG like this should work:
```coffeescript
someInput.input.maxlength = 100
```

**Comment by OskarMG** [comment]
I've tried it with "someInput.input.maxLength" (with the capitalize L) and it worked !! excellent thank you very much !!

**Comment by OskarMG** [comment]
Hi ajimix... Sorry for bother you so long. I'm trying to call the numeric keyboard, but the keyboard always comes char or letters. I only need the numeric one. it is posible? I'm trying this on a real movil device.

**Comment by ajimix** [comment]
Hey @OskarMG whenever you are creating the input, pass the type to be `number`, like the following:
```coffeescript
input = new InputModule.Input
  type: "number"
etc...
```

Take into account that this will appear on mobile.

**Comment by OskarMG** [comment]
yes... The problem is that I'm using a "type" password, because I need the inputs encrypted to be like "••••••", being at the same time numbers.

**Comment by ajimix** [comment]
Ok I see, this will make the desired effect:
```coffeescript
input = new InputModule.Input
  type: "number"

input.style["-webkit-text-security"] = "disc"
```

**Comment by OskarMG** [comment]
It worked, but the maxLength doesn’t want to work when I’m using type: “number”

**Comment by ajimix** [comment]
Yes, type number doesn't accept maxlength. You need to play a bit with the properties, check this [stackoverflow](https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome) question and answers.

One of the options they say is to use type text and use pattern.

I haven't tested it, but code should be like:

```coffeescript
someInput.input.pattern = "\d*"
```

According to that link, that pattern plus maxlength should work when input type is text
