### ISSUE TITLE
virtualKeyboard image ?

### ISSUE THREAD

**Issue by lulato** [ajimix/Input-Framer#28]
when `virtualKeyboard` enabled, it shows up as a question mark. Like is it's missing the image.

**Comment by v12golfcart** [comment]
same issue as lulato - see below

![input issue](https://user-images.githubusercontent.com/28909758/33589542-d2394a8c-d92d-11e7-8103-6fefb9bffedf.gif)

**Comment by ajimix** [comment]
Hello @lulato and @v12golfcart you need to download all files from the project, including the `keyboard.png` which is the missing image.
Once you download the files and put them in the modules folder, the image will appear 😄 
You can replace the image for any other keyboard that you want to have.

I'm closing the issue, please reopen if the issue still persists after doing that.
