### ISSUE TITLE
Please add method .blur()

### ISSUE THREAD

**Issue by dmmat** [ajimix/Input-Framer#29]

**Comment by ajimix** [comment]
Hello @dmmat thanks for your suggestion. I just added it. Please download latest version to have it :)

**Comment by dmmat** [comment]
@ajimix [frame.js] TypeError: undefined is not an object (evaluating 'this._properties[name]')

**Comment by dmmat** [comment]
![photo_2017-12-13_15-51-34](https://user-images.githubusercontent.com/7528598/33942487-bc8e90be-e01e-11e7-955d-2d1fe13bf19b.jpg)

**Comment by ajimix** [comment]
Can you share the project? Did it work with the version before the last I published?

**Comment by dmmat** [comment]
This is new (clean) project, yes it worked before.

**Comment by dmmat** [comment]
I think framer overwrite blur method https://framer.com/docs/#layer.blur

**Comment by ajimix** [comment]
Ok seems like the method name blur cannot be used. I released a new version and renamed it to offFocus: `someInput.offFocus()`

**Comment by ajimix** [comment]
I just saw your PR. Now it's merged and released.

Thanks :)
