### ISSUE TITLE
How to force keyboard open screen load?

### ISSUE THREAD

**Issue by bansalsohil** [ajimix/Input-Framer#31]

**Comment by ajimix** [comment]
Hello @bansalsohil just focus your input like the following

`someInput.focus()`

I'm closing the issue. Please reopen if necessary

**Comment by bansalsohil** [comment]
And someinput.onUnfocus is showing an error that function doesn't exist.

**Comment by ajimix** [comment]
@bansalsohil please use `someInput.onBlur` onUnfocus is wrong, I just removed from the readme.

Thanks
