### ISSUE TITLE
Switch the keyboard to numbers

### ISSUE THREAD

**Issue by tomasbana** [ajimix/Input-Framer#35]
Hi,
it is possible to enable numeric keyboard by default?

Thanks

**Comment by ajimix** [comment]
Yes it's possible, just create the input with type: "number" as seen in the following example:

```coffeescript
input = new InputModule.Input
  y: 240
  x: 90
  width: 500
  height: 60
  type: "number"
```

Please note that the effect will only work on mobile. If you preview your prototype on desktop, the same image will be displayed. If you want the numeric keyboard in desktop, just replace the image with a numeric keyboard.
