### ISSUE TITLE
Is there any way to Bold text within the textarea?

### ISSUE THREAD

**Issue by foopz** [ajimix/Input-Framer#38]
As the title says is there anyway to bold text within the text area? Thanks

**Comment by ajimix** [comment]
yes! Just change the font weight to your desired one like the following:

```coffeescript
input = new InputModule.Input
  fontWeight: "500"
```

You can also access the styles once the input has been created like the following example:

```coffeescript
input.style =
  fontSize: "30px"
  lineHeight: "30px"
  padding: "10px"
  color: "white"
```

**Comment by foopz** [comment]
Sorry, I should have been a little clearer. Is it possible to bold certain words within the textarea? Like, wrapping a word in <bold> tags?

**Comment by ajimix** [comment]
No that is not possible to do, if you want to do that you will have to build something custom
