### ISSUE TITLE
Cannot dismiss keyboard

### ISSUE THREAD

**Issue by jonmadison** [ajimix/Input-Framer#5]
on the desktop, the keyboard is dismissed upon moving to a new screen (or input otherwise submits), but on the device, i have to manually hit "done". any ideas?

**Comment by ajimix** [comment]
Yes that is the expected behavior, you can dismiss the keyboard on mobile on blur easily. Check the following code example:

``` coffeescript
InputModule = require "input"

input = new InputModule.Input

input.onBlur ->
  InputModule.keyboardLayer.states.switch "default"
```

I hope it helps :)

**Comment by jonmadison** [comment]
Thanks! I had figured it out earlier and forgot to come and close this out. 

Yours looks more proper, i went a level below and did a
    document.activeElement.blur()

(the element was apparently still maintaining focus across transitions)
