### ISSUE TITLE
Dismiss keyboard on mobile?

### ISSUE THREAD

**Issue by aalokt89** [ajimix/Input-Framer#9]
On desktop, you are able to dismiss the keyboard when you click out of the input field, but on mobile, this does not happen. Is there a way you can easily do this on mobile?

**Comment by ajimix** [comment]
Hey @aalokt89 it should be dismissed automatically as that is the behaviour of the browser, but if that doesn't happen, you can make it go away with something like this:

```coffeescript
someInput.onBlur ->
    someInput.input.blur()
```

That should work

**Comment by ronanrooney** [comment]
I figured out how to do it a second ago by modifying the CSS string inside the module. Add "outline: none" to the end of this code.

		@input.style.cssText = "font-size: #{options.fontSize}px; line-height: #{options.lineHeight}px; padding: #{options.padding}px; width: #{options.width}px; height: #{options.height}px; border: none; outline-width: 0; background-image: url(about:blank); background-color: #{options.backgroundColor}; outline: none;"

**Comment by ajimix** [comment]
@ronanrooney what has the outline to do with the focus? I don't get it sorry 😕

**Comment by oryan** [comment]
So the solution above doesn't work for me on iOS Safari.

For anyone who arrives here via google searching for a solution, this worked for me reliably:
```
document.activeElement.blur()
```

It may be important to note that this is javascript and not coffeescript, but in Framer mixing the two (within reason) tends to work fine.
